# Generated by Django 4.1.3 on 2023-03-16 20:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_ticketreply_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
