# Generated by Django 4.1.7 on 2023-04-03 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_complaint_deposition_complaints_disposition_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalcontact',
            options={'verbose_name': 'Additional Contact', 'verbose_name_plural': 'Additional Contacts'},
        ),
        migrations.AlterModelOptions(
            name='complaints',
            options={'verbose_name': 'Complaint', 'verbose_name_plural': 'Complaints'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Price', 'verbose_name_plural': 'Prices'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='terms',
            options={'verbose_name': 'Terms of use', 'verbose_name_plural': 'Terms of use'},
        ),
        migrations.AlterModelOptions(
            name='voilation',
            options={'verbose_name': 'Voilation', 'verbose_name_plural': 'Voilations'},
        ),
        migrations.CreateModel(
            name='Userpayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_payment', models.IntegerField(default=0)),
                ('recent_payment', models.IntegerField(default=0)),
                ('recent_payment_is_yearly', models.BooleanField(default=False)),
                ('customer_token', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_token', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Payment',
                'verbose_name_plural': 'User Payments',
            },
        ),
    ]
