# Generated by Django 4.1.7 on 2023-04-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_complaints_link_property_active_voilations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voilation',
            name='link',
            field=models.URLField(blank=True, max_length=1200, null=True),
        ),
    ]
