# Generated by Django 4.1.7 on 2023-06-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_property_violations_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='token',
            new_name='first_month_token',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='yearly_token',
            new_name='first_year_token',
        ),
        migrations.RemoveField(
            model_name='price',
            name='is_popular',
        ),
        migrations.AddField(
            model_name='price',
            name='product_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='subsequent_months_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='subsequent_years_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_per_month',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_per_year',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
