# Generated by Django 4.1.7 on 2023-06-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_token_price_first_month_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='price_change_to_month',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='price_change_to_year',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
