# Generated by Django 4.1.7 on 2023-08-01 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_price_price_change_to_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpayments',
            old_name='recent_payment',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='userpayments',
            old_name='recent_payment_is_yearly',
            new_name='payment_is_yearly',
        ),
        migrations.RemoveField(
            model_name='userpayments',
            name='total_payment',
        ),
    ]
