# Generated by Django 4.1.7 on 2023-10-06 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_recent_payment_userpayments_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HPDComplaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.CharField(blank=True, max_length=100, null=True)),
                ('problem_id', models.CharField(blank=True, max_length=100, null=True)),
                ('complaint_id', models.CharField(blank=True, max_length=100, null=True)),
                ('building_id', models.CharField(blank=True, max_length=100, null=True)),
                ('apartment', models.CharField(blank=True, max_length=100, null=True)),
                ('community_board', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_type', models.CharField(blank=True, max_length=100, null=True)),
                ('space_type', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('major_category', models.CharField(blank=True, max_length=100, null=True)),
                ('minor_category', models.CharField(blank=True, max_length=100, null=True)),
                ('problem_code', models.CharField(blank=True, max_length=100, null=True)),
                ('complaint_status', models.CharField(blank=True, max_length=100, null=True)),
                ('complaint_status_date', models.CharField(blank=True, max_length=100, null=True)),
                ('problem_status', models.CharField(blank=True, max_length=100, null=True)),
                ('problem_status_date', models.CharField(blank=True, max_length=100, null=True)),
                ('status_description', models.TextField(blank=True, null=True)),
                ('council_district', models.CharField(blank=True, max_length=100, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hpd_complaints', to='main.property')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hpd_complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HPD Complaint',
                'verbose_name_plural': 'HPD Complaints',
            },
        ),
    ]
