# Generated by Django 4.1.7 on 2023-11-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_hpdviolations_hpdrepair_hpdlitigation_hpdcharges_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='komal')),
            ],
        ),
    ]
